# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

inhibit_all_warnings!
target 'MVVMCRXSWIFT' do
  use_frameworks!

pod 'Alamofire', ‘4.7’
pod 'AlamofireImage', '~> 3.3.0’
pod 'OHHTTPStubs'
pod 'OHHTTPStubs/Swift'
pod 'ReactiveCocoa', '~> 7.2.0'
pod 'RxSwift', '~> 4.1.2'
pod 'RxCocoa', '~> 4.1.2'
pod 'RxAlamofire'


end 

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'MVVMCRXSWIFTTests' do
  use_frameworks!

pod 'Alamofire', ‘4.7’
pod 'AlamofireImage', '~> 3.3.0’
pod 'OHHTTPStubs'
pod 'OHHTTPStubs/Swift'
pod 'ReactiveCocoa', '~> 7.2.0'
pod 'RxSwift', '~> 4.1.2'
pod 'RxCocoa', '~> 4.1.2'
pod 'RxAlamofire'
pod 'RxBlocking', '~> 4.0'
pod 'RxTest',     '~> 4.0'
testing_pods

end

target 'MVVMCRXSWIFTUITests' do
  use_frameworks!

pod 'Alamofire', ‘4.7’
pod 'AlamofireImage', '~> 3.3.0’
pod 'OHHTTPStubs'
pod 'OHHTTPStubs/Swift'
pod 'ReactiveCocoa', '~> 7.2.0'
pod 'RxSwift', '~> 4.1.2'
pod 'RxCocoa', '~> 4.1.2'
pod 'RxAlamofire'
pod 'RxBlocking', '~> 4.0'
pod 'RxTest',     '~> 4.0'
testing_pods

end

